project:
  type: website

website:
  title: "GWmodel3"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: 开始
        file: index.qmd
      - section: 教程
        contents:
          - tutorial-gwr-basic.qmd
          - tutorial-gwr-multiscale.qmd
          - tutorial-gwdr.qmd

format:
  html:
    theme: default
    toc: true
    lang: zh